<html>
<head>
<script src="../../http/tests/inspector/inspector-test.js"></script>
<script src="../../http/tests/inspector/console-test.js"></script>
<script>

function test()
{
    InspectorTest.reloadPage(function() {
        InspectorTest.expandConsoleMessages();
        InspectorTest.dumpConsoleMessages();
        InspectorTest.completeTest();
    });
}

function evalSource()
{
    function b()
    {
        throw new Error("Exception in eval.");
    }

    function a()
    {
        b();
    }

    a();
}

eval("(" + evalSource + ")()//@ sourceURL=evalURL.js");

</script>
</head>

<body onload="runTest()">
<p>
Tests that when uncaught exception in eval'ed script ending
with //@ sourceURL=url is logged into console, its stack trace
will have the url as the script source. <a href="https://bugs.webkit.org/show_bug.cgi?id=47252">Bug 47252.</a>
</p>

</body>
</html>
